version: '3.8'

services:
  # API Backend ASP.NET Core
  ratiomaster-api:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=ratiomaster-db;Database=RatioMasterDB;User=sa;Password=YourStrong@Password;
      - Redis__ConnectionString=ratiomaster-redis:6379
    volumes:
      - ./data/sessions:/app/data/sessions
      - ./data/logs:/app/data/logs
    depends_on:
      - ratiomaster-db
      - ratiomaster-redis
    networks:
      - ratiomaster-network
    restart: unless-stopped

  # Frontend React
  ratiomaster-web:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_WS_URL=ws://localhost:5000/hub
    depends_on:
      - ratiomaster-api
    networks:
      - ratiomaster-network
    restart: unless-stopped

  # Base de données pour persistance
  ratiomaster-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Password
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - ratiomaster-db-data:/var/opt/mssql
    networks:
      - ratiomaster-network
    restart: unless-stopped

  # Redis pour cache et sessions
  ratiomaster-redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ratiomaster-redis-data:/data
    networks:
      - ratiomaster-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Reverse proxy Nginx
  ratiomaster-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - ratiomaster-web
      - ratiomaster-api
    networks:
      - ratiomaster-network
    restart: unless-stopped

networks:
  ratiomaster-network:
    driver: bridge

volumes:
  ratiomaster-db-data:
    driver: local
  ratiomaster-redis-data:
    driver: local
